jwt_token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDI2MDc0Mzh9.wn2UqalY-5xJDOPqdPKjHe1hxlCB9fap0LpxIKfxaUA"
out_service_url: "http://proxy-service.in.net.ex:8080/api/v1/add" # Имя контейнера в сети Docker